when trying to beginthe DM TEST, this message shows:
Application error: a client-side exception has occurred while loading studio--mwp-dm-test-5.us-central1.hosted.app (see the browser console for more information).

Console shows:
/dashboard/practice/verbal-reasoning?_rsc=1ucod:1

           Failed to load resource: the server responded with a status of 404 ()
/dashboard/practice/quantitative-reasoning?_rsc=1ucod:1

           Failed to load resource: the server responded with a status of 404 ()
684-19f098c167ed3daa.js:1 Error fetching questions from Firestore: FirebaseError: Missing or insufficient permissions.
window.console.error @ 684-19f098c167ed3daa.js:1
page-b9db860008a5e7cc.js:1 Uncaught ReferenceError: Button is not defined
    at ey (page-b9db860008a5e7cc.js:1:36018)
    at lS (4bd1b696-57d7e958a3b6c634.js:1:39319)
    at ot (4bd1b696-57d7e958a3b6c634.js:1:64567)
    at ov (4bd1b696-57d7e958a3b6c634.js:1:75632)
    at ic (4bd1b696-57d7e958a3b6c634.js:1:112354)
    at 4bd1b696-57d7e958a3b6c634.js:1:112199
    at is (4bd1b696-57d7e958a3b6c634.js:1:112207)
    at u9 (4bd1b696-57d7e958a3b6c634.js:1:109418)
    at iH (4bd1b696-57d7e958a3b6c634.js:1:130644)
    at MessagePort.w (684-19f098c167ed3daa.js:1:26075)
684-19f098c167ed3daa.js:1 Error fetching questions from Firestore: FirebaseError: Missing or insufficient permissions.
window.console.error @ 684-19f098c167ed3daa.js:1
page-b9db860008a5e7cc.js:1 Uncaught ReferenceError: Button is not defined
    at ey (page-b9db860008a5e7cc.js:1:36018)
    at lS (4bd1b696-57d7e958a3b6c634.js:1:39319)
    at ot (4bd1b696-57d7e958a3b6c634.js:1:64567)
    at ov (4bd1b696-57d7e958a3b6c634.js:1:75632)
    at ic (4bd1b696-57d7e958a3b6c634.js:1:112354)
    at 4bd1b696-57d7e958a3b6c634.js:1:112199
    at is (4bd1b696-57d7e958a3b6c634.js:1:112207)
    at u9 (4bd1b696-57d7e958a3b6c634.js:1:109418)
    at iH (4bd1b696-57d7e958a3b6c634.js:1:130644)
    at MessagePort.w (684-19f098c167ed3daa.js:1:26075)